---
title: "Verificate GEOtop point simulation"
author: "JBr"
date: "25. Juni 2015"
output: html_document
runtime: shiny
---

***

This R Markdown document is made interactive using Shiny. To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

***

```{r, include=FALSE}


if(!require(AnalyseGeotop))
{
  if(!require(devtools))
  {
    install.packages(devtools)
    require(devtools)
  }
  install_github("AnalyseGeotop", "JBrenn")
  require(AnalyseGeotop)
}

if(!require(dygraphs))
{
  install.packages(dygraphs)
  require(dygraphs)
}

if(!require(hydroGOF))
{
  install.packages(hydroGOF)
  require(hydroGOF)
}

data("PointOutValidation_sim0007_1D_HiResAlp")
#data("PointOutValidation_sim0011_1D_HiResAlp")
data("observations_B2")
data("lookup_tbl_observation")

time(B2_h)$mday <- time(B2_h)$mday - 1
time(B2_d) <- time(B2_d) - 1

obs <- list(hour=B2_h, day=B2_d)

```

## Inputs and Output

```{r, echo=FALSE}
inputPanel(
  #textInput(inputId = "simFolder", label = "Simulation folder", value = "")
  
  selectInput(inputId = "variable", label = "discover variable", choices = names(B2_d)),
  
  radioButtons(inputId = "aggregation", label = "aggregation", choices = c("hour","day","month"), selected = "day", inline = FALSE),
  
  radioButtons(inputId = "flux_amount", label = "flux or amount", choices = c("flux","amount"), selected = "flux", inline = FALSE)
  
  #submitButton(text = "apply changes")
  
)

```

***

```{r, echo=FALSE}

renderDygraph({
  if (input$aggregation=="hour" | input$aggregation=="day")
  {
    observation <- obs[[input$aggregation]][,input$variable]
  } else observation <- obs[["day"]][,input$variable]
  
  simulation <- var_out[[input$variable]]
  
  if (input$aggregation=="day" & input$flux_amount=="flux") simulation <- aggregate(simulation, as.Date(time(simulation)), mean, na.rm=T) 
  if (input$aggregation=="day" & input$flux_amount=="amount") simulation <- aggregate(simulation, as.Date(time(simulation)), sum, na.rm=F)
  if (input$aggregation=="month" & input$flux_amount=="flux") 
  {
    simulation <- aggregate(simulation, as.yearmon(time(simulation)), mean, na.rm=T)
    observation <- aggregate(observation, as.yearmon(time(observation)), mean, na.rm=T)
  } 
  if (input$aggregation=="month" & input$flux_amount=="amount") 
  {
    simulation <- aggregate(simulation, as.yearmon(time(simulation)), sum, na.rm=F)
    observation <- aggregate(observation, as.yearmon(time(observation)), sum, na.rm=F)
  } 
  
  data <- merge(observation, simulation)
  
  name <- input$variable
  if (grepl("soil_moisture_content",input$variable)) name <- "soil_moisture_content"
  if (grepl("soil_temperature", input$variable)) name <- "soil_temperature"
  if (grepl("liquid_soil_water_pressure", input$variable)) name <- "liquid_soil_water_pressure"
   
  units <- lookup_tbl_observation$unit[lookup_tbl_observation$obs_var==name]
  
  dygraph(data, ylab=paste("[",units,"]",sep="")) %>%
    dyRangeSelector() %>%
    dyRoller()
    
})

```

***

```{r, echo=FALSE}

renderDataTable({
 if (input$aggregation=="hour" | input$aggregation=="day")
  {
    observation <- obs[[input$aggregation]][,input$variable]
  } else observation <- obs[["day"]][,input$variable]
  
  simulation <- var_out[[input$variable]]
  
 if (input$aggregation=="day" & input$flux_amount=="flux") simulation <- aggregate(simulation, as.Date(time(simulation)), mean, na.rm=T) 
  if (input$aggregation=="day" & input$flux_amount=="amount") simulation <- aggregate(simulation, as.Date(time(simulation)), sum, na.rm=F)
  if (input$aggregation=="month" & input$flux_amount=="flux") 
  {
    simulation <- aggregate(simulation, as.yearmon(time(simulation)), mean, na.rm=T)
    observation <- aggregate(observation, as.yearmon(time(observation)), mean, na.rm=T)
  } 
  if (input$aggregation=="month" & input$flux_amount=="amount") 
  {
    simulation <- aggregate(simulation, as.yearmon(time(simulation)), sum, na.rm=F)
    observation <- aggregate(observation, as.yearmon(time(observation)), sum, na.rm=F)
  } 
  
  data <- merge(observation, simulation)
  
  gofs <- gof(sim = data$simulation, obs=data$observation, na.rm = T)
  gofs <- as.data.frame(gofs)
  names(gofs) <- "VALUE"
  gofs$GOF <- dimnames(gofs)[[1]]
  gofs <- gofs[,c(2,1)]
})

```
